batch=$1
batch_ensemble=$2
normalization=1
selection_method="mixed"
last_layer=0
avg=$3
device=$4
dr_method='[\"noDimensionReduction\",0.3]'
rm -f exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
# For data generation
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 10 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 10 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 10 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 2 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 5 --label_distribution --K 2 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh


## For cifar100
# For party number of 100
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 20 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 30 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 50 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 60 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 70 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 80 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh


# For party number of 200
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 30 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 50 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 80 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 100 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 120 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 140 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 170 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh

# For party number of 50
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 20 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 30 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 40 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh

# For party number of 5
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 5 --label_distribution --K 3 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 5 --label_distribution --K 4 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh

# For party number of 10
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 3 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 5 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 6 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 7 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo "python -u ensemble_selection_baselines.py --split cifar10 --model $5 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 10 --label_distribution --K 8 --batch $batch --avg $avg --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --device $device --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$avg.sh