batch=$1
batch_ensemble=$2
dr=$3
dr_method='[\"'$dr'\",0.3]'
model=$4
label_distribution=$5
selection_method=$6
last_layer=$7
layer=$8
name=$9
normalization=1
avg="none"
input_channels=3
num_classes=100

echo "Clustering", $batch, $batch_ensemble, $dr, $model, $label_distribution, $selection_method, $last_layer, $layer, $name, $normalization, $avg, $input_channels, $num_classes

rm -f exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh

# For data generation
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 5 --label_distribution $label_distribution --K 2 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 2 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh

## For cifar100
# For party number of 10
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 5 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 6 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 7 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 10 --label_distribution $label_distribution --K 8 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh


# For party number of 20
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 5 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 8 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 10 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 12 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 14 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 20 --label_distribution $label_distribution --K 17 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh

# For party number of 5
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 5 --label_distribution $label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $model --dataset cifar100 --input_channels $input_channels --num_classes $num_classes --avg $avg --layer $layer --party_num 5 --label_distribution $label_distribution --K 4 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$name.sh