batch=$1
batch_ensemble=$2
normalization=1
selection_method="mixed"
dr_method='[\"noDimensionReduction\",0.3]'
rm -f exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh

## For cifar10
# For party number of 100
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 2 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 5 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 6 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 7 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 10 --label_distribution --K 8 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh


# For party number of 200
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 5 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 8 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 10 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 12 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 14 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 20 --label_distribution --K 17 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh

# For party number of 50
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 5 --label_distribution --K 2 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 5 --label_distribution --K 3 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh
echo "python -u ensemble_selection_clustering.py --split cifar100 --model $3 --dataset cifar100 --input_channels 3 --num_classes 100 --party_num 5 --label_distribution --K 4 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_label_distribution.sh