batch=$1
batch_ensemble=$2
normalization=1
selection_method="mixed"
last_layer=0
dr=$3
dr_method='[\"'$dr'\",0.3]'
rm -f exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
# For data generating
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 10 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 10 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 10 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh


## For cifar10
# For party number of 100
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 20 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 30 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 50 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 60 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 70 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 100 --label_distribution --K 80 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh


# For party number of 200
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 30 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 50 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 80 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 100 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 120 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 140 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 200 --label_distribution --K 170 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo wait >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh

# For party number of 50
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 20 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 30 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh
echo "python -u ensemble_selection_clustering.py --split cifar10 --model $4 --dataset cifar10 --input_channels 3 --num_classes 10 --party_num 50 --label_distribution --K 40 --batch $batch --batch_ensemble $batch_ensemble --selection_method $selection_method --normalization $normalization --last_layer $last_layer --dr_method $dr_method >> exp_results/logs/batch_$batch_ensemble.log 2>> exp_results/logs/batch_$batch_ensemble.log &" >> ../exp_results/shells/batch_ensemble_$batch_ensemble\_$dr.sh